### PR TITLE
#142 Adds missing artifacts to TCK module; updates WFLY and Plugins v…

### LINKED ISSUE #142: CNFEs when running Concurrency TCK
When running Concurrency's TCK there is a CNFE being logged:
```
17:18:29,970 ERROR [io.undertow.request] (default task-2) UT005023: Exception handling request to /test-f1a7a88b-4e54-49f0-842b-92251924396a/ArquillianServletRunnerEE9: java.lang.NoClassDefFoundError: com/beust/jcommander/ParameterException
    at deployment.test-f1a7a88b-4e54-49f0-842b-92251924396a.war//org.jboss.arquillian.testng.container.TestNGTestRunner.execute(TestNGTestRunner.java:41)
    at deployment.test-f1a7a88b-4e54-49f0-842b-92251924396a.war//org.jboss.arquillian.protocol.servlet5.runner.ServletTestRunner.executeTest(ServletTestRunner.java:139)
    at deployment.test-f1a7a88b-4e54-49f0-842b-92251924396a.war//org.jboss.arquillian.protocol.servlet5.runner.ServletTestRunner.execute(ServletTestRunner.java:117)
    at deployment.test-f1a7a88b-4e54-49f0-842b-92251924396a.war//org.jboss.arquillian.protocol.servlet5.runner.ServletTestRunner.doGet(ServletTestRunner.java:86)
```

### PR DESCRIPTION
**Pull request by emmartins**
…ersions

resolves #142

### CODE REVIEW

**Comment by emmartins** [comment]
I think the fail is the usual intermittent.

**Comment by jamezp** [comment]
I think we need to wait for #141 before we merge this and we'll need to create the 31.x branch before this is merged.

**Comment by jamezp** [comment]
> I think the fail is the usual intermittent.

It is which is something we should look at :)

**Comment by emmartins** [comment]
any idea when will #141 be merged? I would like to start playing around wrt the intermitent fail and possible tck component upgrades but doing so with the current issues makes little sense

**Comment by jamezp** [comment]
This needs a rebase now. #141 is merged.

**Comment by emmartins** [comment]
@jamezp rebased

**Review by jamezp — APPROVED** [review]

**Pull request merged**
