### PR TITLE
configures the server to have stateless ejb pool with max size value …

### PR DESCRIPTION
**Pull request by emmartins**
…as 1

### CODE REVIEW

**Comment by emmartins** [comment]
@jamezp @scottmarlow please check if this fixes the 2 intermittent fails for you

**Review by jamezp — APPROVED** [review]
I don't see what this could hurt.

**Comment by jamezp** [comment]
Hmm... ...this failed for me locally. I'm going to give it another run to see if the same tests fail. I had 36 failures, but it looked like CI passed. However, it's a bit out of sync with upstream so that could be why.

**Comment by jamezp** [comment]
Same failures. I'm converting this to a draft for right now so it doesn't get merged by mistake. I'll try to have a look at the failures a bit later.

**Comment by jamezp** [comment]
This seems okay. I'll merge it. I must have had a weird environment setup. I opened up a new terminal and it all passed and went well. Sorry about that, I'll get it merged.

**Pull request merged**
