### PR TITLE
[Issue_166] Add the ability to exclude Faces new TCK tests; exclude challenge #1935 tests

### LINKED ISSUE #166: Exclude Faces #1935 tests on SE 21
If the https://github.com/jakartaee/faces/issues/1935 challenge is accepted and the spec agrees that WildFly can work around the problem by ignoring the problematic tests on SE 21, we should do so.

### PR DESCRIPTION
**Pull request by bstansberry**
Resolves #166 against the 33.x branch

Upstream: #168

### CODE REVIEW

**Review by jamezp — APPROVED** [review]

**Comment by bstansberry** [comment]
I just updated this to remove a cruft file.

**Review by jamezp — APPROVED** [review]

**Review by jasondlee — APPROVED** [review]
This looks good to me, other than the XML formatting, but that's a non-functional nit. :)

**Comment by bstansberry** [comment]
yeah, my non-IDE text editor loves to use tabs in xml

**Comment by bstansberry** [comment]
Thanks @jamezp @jasondlee and @scottmarlow

**Pull request merged**
